// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// DEBUG: Log Supabase configuration in development (remove after OAuth is working)
if (import.meta.env.DEV) {
  console.log('[Supabase Debug] URL:', SUPABASE_URL);
  console.log('[Supabase Debug] Key format valid (starts with eyJ):', SUPABASE_PUBLISHABLE_KEY?.startsWith('eyJ'));
  console.log('[Supabase Debug] Key length:', SUPABASE_PUBLISHABLE_KEY?.length);
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('[Supabase Debug] Missing environment variables!');
  }
  if (SUPABASE_PUBLISHABLE_KEY && !SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
    console.error('[Supabase Debug] WARNING: Anon key does not appear to be a valid JWT. Expected format: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...');
  }
}

// Import the supabase client like this:
// import { supabase } from "'integrations/supabase/client"' (see below for file content);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});